### ISSUE TITLE
How to use Fluent Design?

### ISSUE THREAD

**Issue by DIMANRUS** [OfficeDev/ui-fabric-android#1]
Can you show how to use Fluent with a specific example? Namely, on Xamarin.Android and Xamarin.IOS.

**Comment by lynamemi** [comment]
At this time the ui-fabric-android and -ios libraries are only written in native Android and iOS because of performance and reliability, but we know there is a need in the community for Xamarin support so we will keep this in mind as the library develops. We know there are ways to interface with Xamarin but have not tested or documented these methods as the library is still quite new.

For native examples, checkout out our [demo app](https://github.com/OfficeDev/ui-fabric-android/tree/master/OfficeUIFabric.Demo).

**Comment by vladfilyakov** [comment]
For now you will have to create wrappers/bridge in Xamarin to use our Fabric controls. Xamarin is aware about Fabric and might provide such wrappers themselves, but you will need to contact them about timing.
